# Generated by Django 3.2.4 on 2021-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=100)),
                ("time_interval", models.IntegerField(default=0)),
                ("priority", models.IntegerField(default=10)),
            ],
            options={
                "db_table": "tasks",
            },
        ),
    ]
