# Generated by Django 3.2.4 on 2021-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
