# Generated by Django 3.2.4 on 2021-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskmodel_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="state",
            field=models.CharField(default="OK", max_length=50),
        ),
    ]
