# Generated by Django 3.2.4 on 2021-06-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checksmodel",
            name="time_interval",
            field=models.IntegerField(default=0),
        ),
    ]
