# Generated by Django 3.2.4 on 2021-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('imap', models.CharField(max_length=50)),
                ('smtp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
