# Generated by Django 3.2.4 on 2021-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskToRuleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_id", models.CharField(max_length=100)),
                ("task_id", models.IntegerField(default=0)),
                ("rule_id", models.CharField(default="N/A", max_length=50)),
            ],
            options={
                "db_table": "task_rules",
            },
        ),
    ]
