# Generated by Django 3.2.4 on 2021-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='range',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
