# Generated by Django 3.2.4 on 2021-07-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskmodel_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="message",
            field=models.CharField(default="N/A", max_length=500),
        ),
    ]
